baseurl = "http://derekspace.ddns.net/"
languageCode = "en-us"
title = "Derek's Blog"
theme = "hugo_theme_robust"
metaDataFormat = "json"

[Params]
  Author = "Derek Stich"
  disqusShortname = "hugo-2"
